<?php

namespace AR\BankingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankingRepository extends EntityRepository
{
    public function findByAccount($accountId)
    {
        return $this->findBy(['account' => $accountId]);
    }

    public function findByAccountWithinPeriod($accountId, $startDate, $endDate)
    {
        $query = $this->createQueryBuilder('b')
            ->where('b.account = :accountId')
            ->andWhere('b.date BETWEEN :startDate AND :endDate')
            ->setParameter('accountId', $accountId)
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getQuery();

        return $query->getResult();
    }
}
