<?php

namespace AR\BankingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankingRepository extends EntityRepository
{
    public function findAllFromAccount($accountId)
    {

    }
}
