parameters:
#    ar_banking.example.class: AR\BankingBundle\Example

services:
#    ar_banking.example:
#        class: %ar_banking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
